id=datagrip
name=DataGrip
description=Install the latest stable JetBrains DataGrip Linux application bundle
network=required
privilege=system
interactive=yes
architectures=amd64
verification=sha256-required
