id=google-cloud-cli
name=Google Cloud CLI
description=Install Google's signed APT repository, Cloud CLI, and selected optional packages
network=required
privilege=system
interactive=no
architectures=amd64
verification=signature-required
lifecycle=install-update-uninstall-purge
option=google-cloud-cli-anthos-auth
option=google-cloud-cli-app-engine-go
option=google-cloud-cli-app-engine-grpc
option=google-cloud-cli-app-engine-java
option=google-cloud-cli-app-engine-python
option=google-cloud-cli-app-engine-python-extras
option=google-cloud-cli-bigtable-emulator
option=google-cloud-cli-cbt
option=google-cloud-cli-cloud-build-local
option=google-cloud-cli-cloud-run-proxy
option=google-cloud-cli-config-connector
option=google-cloud-cli-datastore-emulator
option=google-cloud-cli-firestore-emulator
option=google-cloud-cli-gke-gcloud-auth-plugin
option=google-cloud-cli-kpt
option=google-cloud-cli-kubectl-oidc
option=google-cloud-cli-local-extract
option=google-cloud-cli-minikube
option=google-cloud-cli-nomos
option=google-cloud-cli-pubsub-emulator
option=google-cloud-cli-skaffold
option=google-cloud-cli-spanner-emulator
option=google-cloud-cli-terraform-tools
option=google-cloud-cli-tests
option=kubectl
